### ISSUE TITLE
Poloniex todo

### ISSUE THREAD

**Issue by wolffan** [balancemymoney/balance-open#103]
- [x] When key/secret are incorrect we need to detect and fail login (atm it things is got good data) (the error is just a string unformated)
- [x] Report the login errors to UI
 - [x] When login is successful we need to transition properly to the accounts page (atm it's not)

**Comment by ricburton** [comment]
🙌

**Comment by einsteinx2** [comment]
@wolffan fixing the animation issue. The problem is that it was not being called from the main thread. All UI calls **must** always come from the main thread or weird things happen.

To help with this, as a rule, I always call all callback blocks from the main thread. I've also made convenience functions for this. So the easiest way is to do something like this:

Instead of just calling `closeBlock(true)` directly from a network completion handler, wrap it in a call to `async { }` like this (note that `async` is a convenience wrapper for `DispatchQueue.main.async`):

```
async {
    closeBlock(true)
}
```

That will run it asynchronously (next runloop iteration or whatever the dispatch queue equivalent is) on the main thread. 

Doing this at the lowest levels ensures that we can don't have to wrap every layer up in async {} calls to ensure main thread. We just trust that the lowest levels always give us main thread and if we need to do background work, we can use one of the other convenience functions like `DispatchQueue.background.async {}` or `DispatchQueue.utility.async {}` etc depending on thread priority needed.

**Comment by einsteinx2** [comment]
Almost done with this.

**Comment by einsteinx2** [comment]
All done in highlander branch

**Comment by wolffan** [comment]
mmm yeah I knew that :).
I think I trapped myself, *usually* the network callbacks where called on main thread (but that might be when I was using a networking framework instead of NSURrequest, my bad)
