### ISSUE TITLE
1.0 UI Changes

### ISSUE THREAD

**Issue by einsteinx2** [balancemymoney/balance-open#20]
- [x] Modify AccountsTabViewController UI to match mockup #21
- [x] Create vector graphics for the institution buttons #22
- [x] Create vector graphics for the institution headers #28
- [x] Finish implementing UI locking #35

**Comment by ricburton** [comment]
Does this need any design work @einsteinx2?

**Comment by einsteinx2** [comment]
Christian is working on the 1.0 mac design now. Will make a new issue when we get it.
