### ISSUE TITLE
1.0 Internal Changes

### ISSUE THREAD

**Issue by einsteinx2** [balancemymoney/balance-open#24]
- [x] Fill in Syncer class syncAccountsAndTransactions function to use new sources #23
- [x] Add Sparkle update framework #25
- [x] Implement cert pinning for Sparkle and all APIs #26
- [x] Change how account balances are stored in the db to facilitate many currency types #32

**Comment by einsteinx2** [comment]
Done
