### ISSUE TITLE
Integrate Poloniex

### ISSUE THREAD

**Issue by einsteinx2** [balancemymoney/balance-open#7]
- [x] Poloniex client side authentication flow #10
~~-Poloniex server side authentication flow #11~~ (not needed)
- [x] Create PoloniexApi struct with static API functions #12
- [x] Create PoloniexAccount object which parses the response #13
- [x] Create function to create native Accounts from PoloniexAccounts #14

**Comment by einsteinx2** [comment]
Done
